debug: false
server:
  port: 80
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/CODA_COMIGO?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: false
        format_sql: false
        ddl-auto: create
  thymeleaf:
    check-template-location: false
